### ISSUE TITLE
How can I access the functions if you have them protected?

### ISSUE THREAD

**Issue by naregkhodanian** [danielcrt/pinata-laravel#1]

**Comment by rawsilence** [comment]
@naregkhodanian It should work if you are accessing the functions via the Facade.
Anyway, those methods should have been public so I just pushed the updates: 
https://github.com/danielcrt/pinata-laravel/commit/2b0285f8c43c344429576d3eb1a1c20336b191bf

**Comment by naregkhodanian** [comment]
@danielcrt Can you push the update to packagist?

**Comment by rawsilence** [comment]
@naregkhodanian Done. Updates available in v0.1.2

**Comment by naregkhodanian** [comment]
Thank you sir!
