### ISSUE TITLE
Upgrade support to laravel 9

### ISSUE THREAD

**Issue by sumitkumar33** [danielcrt/pinata-laravel#2]
Laravel/Support is throwing error due to incompatibility in laravel 9 and package doesn't has guzzlehttp so I've updated in my fork let me know if you want me to remove it. 

https://github.com/sumitkumar33/pinata-sdk

**Comment by rawsilence** [comment]
Thanks for pointing that out. This should be fixed by https://github.com/danielcrt/pinata-laravel/pull/3
I already merged it to main.
